### PR TITLE
Ash tweaks

### PR DESCRIPTION
**Pull request by ash-entwisle**
ton of updates to pretty much everything

### CODE REVIEW

**Comment by ash-entwisle** [comment]
I diddnt notice GPG decided to die on me, all of these commits are mine mb lol

**Review by alex8obrien — CHANGES_REQUESTED** [review]
- Add a conclusion to the supplimentary section
- I will check the bibliography in a bit - it seems off

**Comment by ash-entwisle** [comment]
> Add a conclusion to the supplementary section

supplementary is for non-indexed sections, iirc a conclusion would be indexed. plus some reports don't need a conclusion. if needs be, a user could add in a conclusion on their own if they want

> I will check the bibliography in a bit - it seems off

Cool, I just took it from the template in the freeside repo.

**Comment by ash-entwisle** [comment]
merging with main. will fix bib if issue

**Pull request merged**
